agenda/urls.py
from django.urls import path

from . import views

app_name = 'agenda'

urlpatterns = [
    path('', views.LoginView.as_view(), name='login'),
    path('registro/', views.RegistroView.as_view(), name='registro'),
    path('consulta/', views.ConsultaView.as_view(), name='consulta'),
    path('cliente/<int:id>', views.ClienteView.as_view(), name='cliente'),
    path('conta/<int:id>', views.ContaView.as_view(), name='conta'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('editarCliente/<int:id>', views.EditarClienteView.as_view(), name='editarCliente'),
    path('excluirCliente/<int:id>', views.ExcluirClienteView.as_view(), name='excluirCliente'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
    
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('agenda.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

agenda/models.py
from pyexpat import model
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Categoria(models.Model):
    categoria = models.CharField(max_length=40)
    def __str__(self):
        return f'{self.categoria}'
        
    
class Agenda(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    cliente = models.CharField(max_length=100)
    valor = models.CharField(max_length=10)
    servico = models.ForeignKey(Categoria, on_delete=models.SET_NULL, null=True)
    data = models.DateField()
    horario = models.TimeField()
    descricao = models.TextField(max_length=999)
    concluido = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.cliente}'

agenda/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import Http404
from django.shortcuts import redirect, render
from django.views import View
from pyexpat import model

from .models import Agenda, Categoria


# views here.
class LoginView(View):
    def get(self, request):

        if request.user.is_authenticated:
            return redirect('agenda:conta', request.user.id)

        return render(request, 'agenda/pages/index.html')

    def post(self, request):
        username = request.POST.get('userLog')
        password = request.POST.get('senhaLog')

        user = authenticate(username = username, password = password)

        if user:
            login(request, user = user)

            return redirect('agenda:registro')
        
        return redirect('agenda:login')



class RegistroView(View):


    def get(self, request):
        agenda = Agenda.objects.all().order_by('-id')
        categoria = Categoria.objects.all().order_by('-id')

        if request.user.is_authenticated:
            return render(request, 'agenda/pages/registro.html', context = {
                'agenda':agenda,
                'categorias':categoria,
                'atualRegistro':True,
            })
        else:
            return redirect('agenda:login')

    def post(self, request):
        time     = request.POST.get('time')
        date     = request.POST.get('date')
        category = request.POST.get('category')
        description = request.POST.get('description')
        valor    = request.POST.get('valor')
        registraFiltro = request.POST.get('btn-confirma')

        print(registraFiltro)

        if registraFiltro == 'on':
            client   = request.POST.get('client').capitalize()
            
            if (len(client) == 0) or (len(time) == 0) or (len(date) == 0) or (len(category) == 0) or (len(description) == 0) or (len(valor) == 0):
                raise Http404('deu ruim!')

            novoCadastro = Agenda.objects.create(usuario = request.user, cliente = client, horario = time, data = date, descricao = description, concluido = False, servico = Categoria.objects.get(categoria = category), valor = valor)

            novoCadastro.save()
            
            return redirect('agenda:registro')
        
        categoria =  request.POST.get('novaCategoria')

        if  not categoria is None:
            novaCategoria = Categoria.objects.create(categoria = categoria)
            novaCategoria.save()
            print(categoria)
            
        return redirect('agenda:registro')



class ConsultaView(View):

    def get(self, request):
        if request.user.is_authenticated:
            agenda = Agenda.objects.filter(usuario=request.user, concluido=False).order_by('-id')
            categoria = Categoria.objects.all().order_by('-id')

            return render(request, 'agenda/pages/consulta.html', context = {
                'agenda':agenda,
                'categorias':categoria,
                'category':'Serviço',
                'atualConsulta':True,
            })
        else:
            return redirect('agenda:login')

    def post(self, request):
        client   = request.POST.get('client')
        time     = request.POST.get('time')
        date     = request.POST.get('date')
        category = request.POST.get('category')
        concluido = request.POST.get('verificados')
        pesquisar = request.POST.get('btn-pesquisar')
        if concluido is None:
            concluido = pesquisar.split(' ')[1]
            if concluido == 'on':
                classe = 'verificados_on'
            else:
                classe = 'verificados_off'
        if not pesquisar is None:
            if pesquisar.split(' ')[0]  == 'on':
                conclu = True if concluido == 'on' else False
                print(category)
                print(date)
                print(time)
                print(conclu)
                if category == '':
                    filtrar = Agenda.objects.filter(usuario = request.user, cliente__icontains = client, horario__icontains = time, data__icontains = date, concluido = conclu).order_by('-id')
                else:
                    filtrar = Agenda.objects.filter(usuario = request.user, servico__id =category, cliente__icontains = client, horario__icontains = time, data__icontains = date, concluido = conclu).order_by('-id')
                
                category = 'Serviço'

                categoria = Categoria.objects.all().order_by('-id')
                return render(request, 'agenda/pages/consulta.html', context = {
                    'agenda'    :filtrar,
                    'categorias':categoria,
                    'concluido' :concluido,
                    'classe'    :classe,
                    'client'    :client,
                    'time'      :time,
                    'date'      :date,
                    'category'  :category,
                    'atualConsulta':True,
                })
            
        if concluido == 'on':
            classe = 'verificados_on'
        else:
            classe = 'verificados_off'
        category_id = ''
        if category != '':
            category = Categoria.objects.filter(id=category).first()
            category_id = category.id
        else:
            category = 'Serviço'
        
        agenda = Agenda.objects.filter(usuario=request.user, concluido=False).order_by('-id')
        categoria = Categoria.objects.all().order_by('-id')

        return render(request, 'agenda/pages/consulta.html', context = {
            'agenda'    :agenda,
            'categorias':categoria,
            'concluido' :concluido,
            'classe'    :classe,
            'client'    :client,
            'time'      :time,
            'date'      :date,
            'category'  :category,
            'category_id': category_id,
            'atualConsulta':True,
        })

        if category == '':
            filtro = Agenda.objects.filter(usuario = request.user, categoria__id = category, client__icontains = client, horario__icontains = time, data__icontains = date, concluido = concluido)



class ClienteView(View):
    def get(self, request, id):

        if request.user.is_authenticated:

            publicacao = Agenda.objects.filter(usuario = request.user, id = id)

            for cliente in publicacao:
                nome = cliente.cliente

            return render(request, 'agenda/pages/client.html',
            context = {
                'publicacao':publicacao,
                'nome':nome,
            })
        else:
            return redirect('agenda:login')




class ContaView(View):
    def get(self, request, id):

        if request.user.is_authenticated:
            publicacao = User.objects.filter(username = request.user, id = id)
            for user in publicacao:
                nome = user.username

            return render(request, 'agenda/pages/conta.html',
                context = {
                    'atualConta':True,
                    'nome':nome
                })
        else:
            return redirect('agenda:login')

    def post(self, request, id):

        sair    = request.POST.get('sair')
        salvar    = request.POST.get('salvar')

        if sair == 'on':
            return redirect('agenda:conta', id)

        print(sair, salvar)

        usuario = request.POST.get('username')
        senha   = request.POST.get('password')
        perfil  = User.objects.filter(username = request.user, id = id)

        for user in perfil:
                user.username = usuario
                user.set_password(senha)
                user.save()

        relog = authenticate(request, username = usuario, password = senha)
        login(request, user = relog)

        return redirect('agenda:conta', id)
            

class LogoutView(View):
    def get(self, request):
        if request.user.is_authenticated:
            logout(request)

        return redirect('agenda:login')


class EditarClienteView(View):
    def get(self, request, id):
        if request.user.is_authenticated:
            publicacao = Agenda.objects.filter(usuario = request.user, id = id)
            categorias = Categoria.objects.all()
            nome = publicacao[0].cliente
            return render(request, 'agenda/pages/editarCliente.html', context = {
                'publicacao':publicacao,
                'categorias':categorias,
                'nome':nome,
            })
        else:
            return redirect('agenda:login')

    def post(self, request, id):
        data      = request.POST.get('date')
        hora      = request.POST.get('time')
        categoria = request.POST.get('category')
        nome      = request.POST.get('client')
        valor     = request.POST.get('valor')
        descricao = request.POST.get('description')
        concluido = request.POST.get('concluido')
        print(concluido)
        concluido = False if concluido == None else True

        publicacao = Agenda.objects.filter(usuario=request.user, id=id)
        categorias = Categoria.objects.all().order_by('-id')

        print(data)
        for cliente in publicacao:
            cliente.cliente   = nome
            cliente.categoria = Categoria.objects.get(categoria=categoria)
            cliente.valor     = valor
            cliente.date      = data
            cliente.horario   = hora
            cliente.descricao = descricao
            cliente.concluido = concluido
            cliente.save()
        
        return redirect('agenda:editarCliente', id)

<<<<<<< HEAD




=======
>>>>>>> e01558be9b5875daf2ace8acaee06304da0b5556
class ExcluirClienteView(View):
    def get(self, request, id):
        if request.user.is_authenticated:
            publicacao = Agenda.objects.filter(usuario = request.user, id = id)
            publicacao.delete()

agenda/templates/agenda/pages/consulta.html
{% load static %}

<!doctype html>
<html lang="pt-br">
    <head>
        <title>Consulta de Agenda</title>
        <meta charset="utf-8">
        <link rel="stylesheet"      type="text/css" href="{% static 'css/consulta.css' %}">
        <link rel="stylesheet"      type="text/css" href="{% static 'css/navbar.css'   %}">
        <link rel="stylesheet"      type="text/css" href="{% static 'css/normalize.css'%}">
        <meta name="viewport"       content="width=device-width, initial-scale=1.0">
        <meta name="author"         content="@_josephsl">
        <link rel="icon" type="/" width="25" href="{% static '/img/icon.png' %}"/>
        <!-- fontawesome -->
        <script src="https://kit.fontawesome.com/944a9ba2fe.js" crossorigin="anonymous"></script>
    </head>
    <body>
        
        {% include 'agenda/partials/header.html' %}

        <main>
            <div class="container">
                <h2 id="title"><span class="title">Consulte</span> a Agenda!</h2>
                
                <div class="wrapper">
                    <div class="filtro">
                        <form action="{% url 'agenda:consulta' %}" method="POST">{% csrf_token %}                        
                            <input type="text" value="{{client}}" name="client"   id="client" placeholder="Cliente">
                            
                            <input type="time" value="{{time}}"     name="time"     id="">
                            <input type="date" value="{{date}}"     name="date"     id="">
                            <select            value="{{category}}" name="category" id="">
                                <option        value="{{category_id}}">{{category}}</option>
                                {% if category != 'Serviço'%}
                                        <option value="">Serviço</option>
                                    {% endif %}
                                {% for categoria in categorias %}
                                    {% if  categoria.id != category_id %}
                                        <option value="{{categoria.id}}">{{categoria.categoria}}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                            <button onclick="MostrarVerificados()" name="verificados" id="btn-verificados" value="{{concluido}}" class="btn btn-verificados {{classe}}"><i class="fa-solid fa-check"></i></button>

                            <button onclick="Pesquisar()" value="off" name="btn-pesquisar" id="btn-pesquisar" class="btn btn-pesquisar"><i class="fa-solid fa-magnifying-glass"></i></button>
                        </form>
                    </div><!--filtro-->
                    <table> 
                        <tr>
                            <th>Cliente</th>
                            <th>Valor</th>
                            <th>Serviço</th>
                            <th>Horário</th>
                            <th>Data</th>
                            <th>Ações</th>
                        </tr>
                        {% for cliente in agenda  %}
                                <tr>                                   
                                    <td><a href="{% url 'agenda:cliente' cliente.id %}">{{cliente.cliente}} </a></td>
                                    <td><a href="{% url 'agenda:cliente' cliente.id %}">{{cliente.valor}}   </a></td>
                                    <td><a href="{% url 'agenda:cliente' cliente.id %}">{{cliente.servico}} </a></td>
                                    <td><a href="{% url 'agenda:cliente' cliente.id %}">{{cliente.horario}} </a></td>
                                    <td><a href="{% url 'agenda:cliente' cliente.id %}">{{cliente.data}}    </a></td>
                                    <td>
                                        <a href="{% url 'agenda:editarCliente' cliente.id %}"><button id="acao-confirm" class="btn btn-acao"><i style="font-size: 15px;" class="fa-solid fa-pen"></i></button></a>
                                        <a href="{% url 'agenda:excluirCliente' cliente.id %}"><button id="acao-excluir" class="btn btn-acao"><i class="fa-solid fa-x"></i></button></a>
                                    </td>
                                </tr>
                        {% endfor %}
                    </table>
                </div><!--wrapper-->
            </div><!--container-->
        </main>
    </body>
    <script src="{% static 'js/script.js' %}"></script>
</html>

agenda/templates/agenda/pages/conta.html
{% load static %}

<!doctype html>
<html lang="pt-br">
    <head>
        <title>Sua conta</title>
        <meta charset="utf-8">
        <link rel="stylesheet"      type="text/css" href="{% static 'css/conta.css' %}">
        <link rel="stylesheet"      type="text/css" href="{% static 'css/navbar.css'   %}">
        <link rel="stylesheet"      type="text/css" href="{% static 'css/normalize.css'%}">
        <meta name="viewport"       content="width=device-width, initial-scale=1.0">
        <meta name="author"         content="@_josephsl">
        <link rel="icon" type="/" width="25" href="{% static '/img/icon.png' %}"/>
        <!-- fontawesome -->
        <script src="https://kit.fontawesome.com/944a9ba2fe.js" crossorigin="anonymous"></script>
    </head>
    <body>
        
        {% include 'agenda/partials/header.html' %}

        <main>
            <div id="container" class="container">
                <h2 id="title"><span class="title">Sua</span><span class="title-conta">Conta</span></h2>
                
                <div class="wrapper-tabela">
                    <div class="tabela">
                        <table>
                            <tr>
                                <td><h3>Username:</h3></td>
                                <td><p>{{nome}}</p></td>
                            </tr>
                            <tr>
                                <td><h3>Senha:</h3></td>
                                <td><p style="margin-top: 12px;">******</p></td>
                            </tr>
                            <tr>
                                <td class="botoes" colspan="2">
                                    <button onclick="AlterarDados()">Alterar Dados</button>
                                    <form action="{% url 'agenda:logout' %}">
                                        <button class="encerrarSessao">Encerrar Sessão</button>
                                    </form>
                                </td>
                        </table>
                    </div><!--tabela-->
                    <div class="svg">
                        <img src="{% static 'svg/account.svg' %}" alt="">
                    </div><!--svg-->
                </div><!--wrapper-->
            </div><!--container-->
            <div id="background">               
                <section id="alteraDados">
                    <form action="{% url 'agenda:conta' user.id %}" method="POST">{% csrf_token %}
                        <div class="wrap">                            
                            <span>*Alterar Dados</span>
                            <label for="username">Novo Username*</label>
                            <input type="text" name="username">

                            <label for="password">Nova Senha*</label>
                            <input type="text" name="password">
                        </div><!--wrap-->
                        <div class="botoesAlteraDados">
                            <button name="sair"   value="off" id="btn_sair" onclick="BotaoSair()">Sair</button>
                            <button name="salvar" value="salvar">Salvar</button>
                        </div><!--botoesAlteraDados-->
                    </form>
                </section>
            </div><!--background-->
        </main>
    </body>
    <script src="{% static 'js/script.js' %}"></script>
</html>

agenda/templates/agenda/pages/editarCliente.html
{% load static %}
<!doctype html>
<html lang="pt-br">
    <head>
        <title>Editando: {{nome}}</title>
        <meta charset="utf-8">
        <link rel="stylesheet"      type="text/css" href="{% static 'css/registro.css' %}">
        <link rel="stylesheet"      type="text/css" href="{% static 'css/navbar.css'   %}">
        <link rel="stylesheet"      type="text/css" href="{% static 'css/normalize.css'%}">
        <meta name="viewport"       content="width=device-width, initial-scale=1.0">
        <meta name="author"         content="@_josephsl">
        <link rel="icon" type="/" width="25" href="{% static '/img/icon.png' %}"/>
        <!-- fontawesome -->
        <script src="https://kit.fontawesome.com/944a9ba2fe.js" crossorigin="anonymous"></script>
    </head>
    <body>
        
        {% include 'agenda/partials/header.html' %}

        <main>
            <div class="container">
                <h2 id="title"><span class="title">Editar</span> {{nome}}</h2>
                
                <div class="wrapper">
                    {% for cliente in publicacao %}
                        <form action="{% url 'agenda:editarCliente' cliente.id %}" method="POST">{% csrf_token %}
                            <div class="filtro">
                                <input type="text"      value="{{cliente.cliente}}" id="client" name="client" placeholder="{{cliente.cliente}}">
            
                                <input type="time"      value="{{cliente.horario}}" id="time" name="time">
                                <input type="date"      value="{{cliente.data}}" id="date" name="date">
                                <select name="category" id="">
                                    <option value="{{cliente.servico}}">{{cliente.servico}}</option>

                                    {% for categoria in categorias %}
                                        {%  if cliente.servico !=  categoria.categoria %}
                                            <option value="{{categoria.categoria}}">{{categoria.categoria}}</option>
                                        {% endif %}
                                    {% endfor %}
                                </select>
                            </div><!--filtro-->
                            <div class="filtro filtro2">
                                <input type="text" value="{{cliente.valor}}" name="valor" id="valor" placeholder="{{cliente.valor}}" style="text-align: left;">

                                <input type="text" value="{{cliente.descricao}}" name="description" id="descricao" placeholder="{{cliente.descricao}}">
                                <input type="checkbox" value="{{cliente.concluido}}" name='concluido' class="btn" {% if cliente.concluido %}checked{% endif %}>
                                <button id="btn-confirma" class="btn" style="position: relative; top: -12px;">
                                    <i class="fa-solid fa-check"></i>
                                </button>
                            </div><!--filtro-->
                        </form>
                    {% endfor %}
                </div><!--wrapper-->
            </div><!--container-->
        </main>
    </body>
</html>

agenda/templates/agenda/pages/index.html
{% load static %}

<!doctype html>
<html lang="pt-br">
    <head>
        <title>Agenda: Faça Log-in</title>
        <meta charset="utf-8">
        <link rel="stylesheet"      type="text/css" href="{% static 'css/index.css'    %}">
        <link rel="stylesheet"      type="text/css" href="{% static 'css/navbar.css'   %}">
        <link rel="stylesheet"      type="text/css" href="{% static 'css/normalize.css'%}">
        <meta name="viewport"       content="width=device-width, initial-scale=1.0">
        <meta name="author"         content="@_josephsl">
        <link rel="icon" type="/" width="25" href="{% static '/img/icon.png' %}"/>
    </head>
    <body>

        {% include 'agenda/partials/header.html' %}

        <main>            
            <section>
                <div class="box login">
                    <form  action="{% url 'agenda:login' %}" method="POST">{% csrf_token %}
                        <div class="title">
                            <h2>Faça Log-in</h2>
                        </div>                         
                        <div class="alertBox alertBoxLog"></div>

                        <div class="cad-wrapper">
                            <div class="label-float">
                                <input id="userLog" type="text" name="userLog" required>
                                <label id="userLogLabel" for="userLog">Username:</label>
                            </div><!--label-float-->
                            <div class="label-float">
                                <input id="senhaLog" type="password" name="senhaLog" required>
                                <label id="senhaLogLabel" for="senhaLog">password:</label>
                                <i id="verSenhaLog" class="fa-solid fa-eye-low-vision"></i>
                            </div><!--label-float-->
                        </div><!--cad-wrapper-->
                        <!--<button onclick="entrar()" class="btn btn-login">Entrar</button>-->
                        <input type="submit" onclick="entrar()" class="btn btn-login" value="Entrar">
                    </form>
                </div><!--log-right-->
            </section>
        </main>  
    </body>
</html>

agenda/templates/agenda/pages/registro.html
{% load static %}
<!doctype html>
<html lang="pt-br">
    <head>
        <title>Registro de Clientes</title>
        <meta charset="utf-8">
        <link rel="stylesheet"      type="text/css" href="{% static 'css/registro.css' %}">
        <link rel="stylesheet"      type="text/css" href="{% static 'css/navbar.css'   %}">
        <link rel="stylesheet"      type="text/css" href="{% static 'css/normalize.css'%}">
        <meta name="viewport"       content="width=device-width, initial-scale=1.0">
        <meta name="author"         content="@_josephsl">
        <link rel="icon" type="/" width="25" href="{% static '/img/icon.png' %}"/>
        <!-- fontawesome -->
        <script src="https://kit.fontawesome.com/944a9ba2fe.js" crossorigin="anonymous"></script>
    </head>
    <body>
        
        {% include 'agenda/partials/header.html' %}

        <main>
            <div id="container" class="container">
                <h2 id="title"><span class="title">Registrar</span> Cliente</h2>
                
                <div class="wrapper">
                    <form action="{% url 'agenda:registro' %}" method="POST">{% csrf_token %}
                        <div class="filtro">
                            <input type="text" id="client" name="client" placeholder="Cliente">
        
                            <input type="time" id="time" name="time">
                            <input type="date" id="date" name="date">
                            <select name="category" id="">
                                <option value="">Serviço</option>

                                {% for categoria in categorias %}
                                    <option value="{{categoria.categoria}}">{{categoria.categoria}}</option>
                                {% endfor %}
                            </select>
                        </div><!--filtro-->
                        <div class="filtro filtro2">
                            <input type="text" name="valor"      id="valor"     placeholder="Valor">
                            <input type="text" name="description" id="descricao" placeholder="Descrição">
                            <button onclick="btnConfirma()" name="btn-confirma" id="btn-confirma" value="off" class="btn"><i class="fa-solid fa-check"></i></button>
                        </div><!--filtro-->
                    </form>
                    <button onclick="RegistraFiltro()" value="off" id="btnRegistraFiltro" name="registraFiltro" class="btn btn-editar-categoria">
                        <i class="fa-solid fa-pen-to-square"></i>
                    </button>
                </div><!--wrapper-->
            </div><!--container-->


            <div id="background">               
                <section id="registraFiltro">
                    <form action="{% url 'agenda:registro' %}" method="POST">{% csrf_token %}
                        <div class="wrap">                            
                            <span>*Registrar Nova Categoria:</span>
                            <label for="novaCategoria">Nova categoria*</label>
                            <input type="text" name="novaCategoria">
                        </div><!--wrap-->
                        <div class="botoesAlteraDados">
                            <button name="sair"   value="off" id="btn_sair" onclick="BotaoSair()">Sair</button>
                            <button name="salvar" value="salvar">Salvar</button>
                        </div><!--botoesAlteraDados-->
                    </form>
                </section>
            </div><!--background-->


        </main>
        <script src="{% static 'js/script.js' %}"></script>
    </body>
</html>